Project = "Red Team Simulator"
version = "1.0"
description = "Red Team Campaign Simulator 
is an educational web based cybersecurity 
platform that allows users to create virtual 
network environments, assign CVEs mapped to 
the MITRE ATT&CK framework and simulate 
deterministic red team attack campaigns. 
It provides visual representations of 
attack paths, tracks techniques, and 
generates PDF reports without performing any real network operations."

Author = "Talha Gurmani"

requires-python = ">=3.11 or + "
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "markdown2>=2.5.4",
    "networkx>=3.5",
    "pillow>=12.0.0",
    "reportlab>=4.4.4",
]
